theme: jekyll-theme-cayman
title: 'Scenario Hunting'
tagline: ''

production_url : https://scenariohunting.com
site:
  google_analytics : 'G-QZ35D3WH97'
        
author:
  name: Mohsen Bazmi
  twitter: @MohsenBazmi

description: "Don't code. Model, then solve the puzzle!"
github:
  repository_url: "https://github.com/ScenarioHunting/ScenarioHunting"
