remote_theme: pmarsceill/just-the-docs
theme: jekyll-theme-cayman
title: 'Scenario Hunting'

production_url : https://scenariohunting.com
google_analytics: 'G-QZ35D3WH97'
        
author:
  name: Mohsen Bazmi
  twitter: "@MohsenBazmi"


description: "Switching from modeling space to implementation space."
github:
  repository_url: "https://github.com/ScenarioHunting/ScenarioHunting"
